[project]
name = 'freespace_planner_lib_py'
requires-python = ">=3.10"
version = "0.1.0"
authors = [
    {name = "Oliver Schumann", email = "oliver.schumann@uni-ulm.de"}
]

[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools]
py-modules = ["gridmap_sim_lib", "hybridastar_planning_lib", "path_planner_lib"]